//! Raw FFI bindings to cuDNN
//!
//! This module contains the low-level bindings generated by bindgen.
//! These are wrapped by safer abstractions in other modules.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
